### ISSUE TITLE
TimeStamp attribute not decorated on RowVersion Properties

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#10]
Hi Tony,

While scaffolding RowVersion columns are not decorated with TimeStamp Attribute

**Comment by tonysneed** [comment]
Adding the `TimeStamp` attribute is something you have to do yourself to implement a [concurrency control](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency) strategy.

Because the entities are generated partial classes, you can use [metadata types](https://msdn.microsoft.com/en-us/library/ff664465(v=pandp.50).aspx) to add attributes in your own partial classes.
