### ISSUE TITLE
AddHandlebarsTransformers -> entityNameTransformer - Add schema of object to object name

### ISSUE THREAD

**Issue by BBSquared** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#157]
There's no easy way to add schema in to the object names as far as I can tell.  Would it be possible to make the entityNameTransformer include a more complex object that includes the database schema?  example:

// Add optional Handlebars transformers with Schema
services.AddHandlebarsTransformers(
    entityNameTransformer: o=> o.Schema + "_" + o.Name    
)

*edit: instead of passing IEntityType.Name, just pass IEntityType ?

**Comment by tonysneed** [comment]
Hi @BBSquared, Handlebars Scaffolding supports the concept of [Schema Folders](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/README.md#schema-folders).

When you enable Schema Folders, entities are placed in the schema namespace, which is the same as the folder name (following .NET coding conventions). When you use the schema qualified entities in your code, you can alias the schema namespace, for example, as `dbo.Category`, as shown [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/sample/ScaffoldingSample/Contexts/NorthwindSlimContext.cs) in `NorthwindSlimContext`.

Would this possibly meet your needs?  If not, you have the option of extending`HbsCSharpEntityTypeGenerator` to override `GenerateClass`. You can find instruction [here](https://github.com/TrackableEntities/ef-core-community-handlebars/blob/master/README.md#7-full-control-extend-handlebars-generators).

Regarding your request to pass `IEntityType` instead of `IEntityTypeName`, an overload to `AddHandlebarsTransformers` could be added, but this would require a change to `IEntityTypeTransformationService`, as well as a number of other places.

**Comment by tonysneed** [comment]
Please re-open if there are further questions or concerns.
