### ISSUE TITLE
CodeTemplates folder not copied to output directory on build

### ISSUE THREAD

**Issue by johnwc** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#186]
**Describe the bug**
When using the `--startup-project` option to create the db models and db context in a library, but use the connection string from the main project using "Name=ConnectionString:xxx". I have to put the `ConfigureDesignTimeServices` in the main project, and we get the `System.IO.DirectoryNotFoundException: Could not find a part of the path '....MainProject\bin\Debug\net5.0\CodeTemplates\CSharpDbContext\Partials\DbImports.hbs'.` exception.

**Expected behavior**
Expect it to use the current project, the library project in this case; for checking for `IDesignTimeServices` class. As well as using the current project for creating the CodeTemplates directory.

**To Reproduce**
 1. Create Library project
 2. Create Console/Web project, referencing library project.
 3. Create connection string in Console/Web project named xyz.
 4. Add all required EF core nuget packages to library and console/web project.
 5. Create IDesignTimeServices in console/web project.
 6. Run `dotnet ef dbcontext scaffold "Name=ConnectionStrings:xyz" "<Your DB provider class>" -d --force -o DAL -c XyzContextDb --startup-project ..\MainApp` from library project's directory.

**Comment by johnwc** [comment]
There is two issues pointed out. The main issue is with the DB exception when trying to use connecting string by name from the start up project.

**Comment by tonysneed** [comment]
Where is your appSettings.json file located, which contains [connection string name](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)? It should be in your MainApp.

**Comment by johnwc** [comment]
It is in the project that is pointed at via the `--startup-project` option, aka the MainApp in the example command line.

**Comment by tonysneed** [comment]
I was able to reproduce the issue [here](https://github.com/tonysneed/ConStringNameTest). Will look into the cause.

**Comment by tonysneed** [comment]
The problem is taking place at build-time, not runtime. And it has nothing to do with the `--startup-project` option or using a connection string name.

The project file for EntityFrameworkCore.Scaffolding.Handlebars has a section that copies hbs templates to a `CodeTemplates` folder in the build output directory. For example:

```xml
<None Update="CodeTemplates\CSharpDbContext\Partials\DbImports.hbs">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
```

Sometimes `dotnet build` does not result in the files being copied. When they are not present, this results in a runtime exception when the the library attempts to copy them to the project directory. 

I will investigate this as a bug with NuGet / dotnet build. In the meantime, you can get around this by simply copying the `CodeTemplates` folder to the project root. If it is there, no I/O error will take place.

**Comment by tonysneed** [comment]
Found out how to fix the problem. Created a [demo project](https://github.com/tonysneed/NuGetCopyFiles) on how to copy files from a NuGet package to an output directory.

I'll create a PR to fix the problem for EntityFrameworkCore.Scaffolding.Handlebars.
