### ISSUE TITLE
[Proposal] Add more information about field/entity to propertyTransformer/EntityPropertyInfo

### ISSUE THREAD

**Issue by MyEidos** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#84]
It is hard and sometimes not flexible to use propertyTransformer because of  luck of information inside method. 
It will be great to have next information in  propertyTransformer:
1. Information about current table: name, metadata etc.
2. Information about property in EntityPropertyInfo: metadata etc.

**Comment by tonysneed** [comment]
The transformer methods are, as you point out, limited in terms of what metadata is communicated to the Handlebars template, namely, property name and type. The reason for this is simplicity and performance.

For scenarios where you need to take more control of the transformation process, it is recommended you create a class that extends `HbsCSharpEntityTypeGenerator` and override `GenerateProperties`. Then register your `MyCSharpEntityTypeGenerator` in your `ScaffoldingDesignTimeServices` class. See #61 for detailed instructions.

**Comment by tonysneed** [comment]
@MyEidos Have you tried the approach I suggested with extending `HbsCSharpEntityTypeGenerator`? Does it allow you to achieve what you'd like to accomplish?

**Comment by tonysneed** [comment]
Closing this as resolved. @MyEidos Please let me know if this is not the case.

**Comment by aeslinger0** [comment]
@tonysneed, could this be looked at again? Your proposal to extend `HbsCSharpEntityTypeGenerator` doesn't work well because the base implementation of `GenerateNavigationProperties`, for example, includes references to private members in the base class. Could you either make those references protected or, even more ideally, pass in the objects such as the `INavigation` instance into the navPropertyTransformer?
